# Generated by Django 3.2.24 on 2024-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
