# Generated by Django 3.2.24 on 2024-05-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
